import type { WorkEvent } from "../types/work-event.js";

export function buildDemoWorkEvents(): WorkEvent[] {
  return [
    {
      event_id: "evt_demo_008",
      agent_name: "数据分析",
      event_type: "tool_call",
      tool_type: "record_list",
      target_table: "reports",
      execution_mode: "dry_run",
      guard_status: "passed",
      safe_summary: "数据分析生成招聘漏斗摘要",
      status_before: null,
      status_after: null,
      duration_ms: 102,
      parent_run_id: "run_demo_analytics_001",
      link_status: "demo_only",
      created_at: "2026-04-27T09:12:00.000Z",
    },
    {
      event_id: "evt_demo_007",
      agent_name: "HR 协调",
      event_type: "human_action",
      tool_type: null,
      target_table: "candidates",
      execution_mode: "dry_run",
      guard_status: null,
      safe_summary: "HR 协调将候选人推进到待决策节点",
      status_before: "interview_kit_ready",
      status_after: "decision_pending",
      duration_ms: 58,
      parent_run_id: "run_demo_hr_002",
      link_status: "demo_only",
      created_at: "2026-04-27T09:10:00.000Z",
    },
    {
      event_id: "evt_demo_006",
      agent_name: "面试准备",
      event_type: "status_transition",
      tool_type: "record_upsert",
      target_table: "interview_kits",
      execution_mode: "dry_run",
      guard_status: "passed",
      safe_summary: "面试准备生成结构化面试材料",
      status_before: "screened",
      status_after: "interview_kit_ready",
      duration_ms: 136,
      parent_run_id: "run_demo_interview_001",
      link_status: "demo_only",
      created_at: "2026-04-27T09:08:30.000Z",
    },
    {
      event_id: "evt_demo_005",
      agent_name: "初筛评估",
      event_type: "guard_check",
      tool_type: null,
      target_table: "evaluations",
      execution_mode: "blocked",
      guard_status: "blocked",
      safe_summary: "写入守卫确认当前为只读演示模式",
      status_before: "parsed",
      status_after: "parsed",
      duration_ms: 14,
      parent_run_id: "run_demo_screen_002",
      link_status: "no_link",
      created_at: "2026-04-27T09:07:40.000Z",
    },
    {
      event_id: "evt_demo_004",
      agent_name: "初筛评估",
      event_type: "retry",
      tool_type: "llm_call",
      target_table: null,
      execution_mode: "dry_run",
      guard_status: "skipped",
      safe_summary: "初筛评估重新整理三档匹配建议摘要",
      status_before: "parsed",
      status_after: "screened",
      duration_ms: 88,
      parent_run_id: "run_demo_screen_001",
      link_status: "no_link",
      created_at: "2026-04-27T09:06:20.000Z",
    },
    {
      event_id: "evt_demo_003",
      agent_name: "初筛评估",
      event_type: "tool_call",
      tool_type: "record_upsert",
      target_table: "evaluations",
      execution_mode: "dry_run",
      guard_status: "passed",
      safe_summary: "初筛评估生成三档匹配建议",
      status_before: "parsed",
      status_after: "screened",
      duration_ms: 129,
      parent_run_id: "run_demo_screen_001",
      link_status: "demo_only",
      created_at: "2026-04-27T09:05:10.000Z",
    },
    {
      event_id: "evt_demo_002",
      agent_name: "简历解析",
      event_type: "status_transition",
      tool_type: "record_upsert",
      target_table: "resume_facts",
      execution_mode: "dry_run",
      guard_status: "passed",
      safe_summary: "简历解析完成候选人资料结构化提取",
      status_before: "new",
      status_after: "parsed",
      duration_ms: 118,
      parent_run_id: "run_demo_resume_001",
      link_status: "demo_only",
      created_at: "2026-04-27T09:03:20.000Z",
    },
    {
      event_id: "evt_demo_001",
      agent_name: "HR 协调",
      event_type: "tool_call",
      tool_type: "record_list",
      target_table: "candidates",
      execution_mode: "dry_run",
      guard_status: "passed",
      safe_summary: "HR 协调加载候选人待处理队列",
      status_before: null,
      status_after: "new",
      duration_ms: 42,
      parent_run_id: "run_demo_hr_001",
      link_status: "no_link",
      created_at: "2026-04-27T09:01:00.000Z",
    },
  ];
}
